# Generated by Django 5.1.2 on 2024-12-02 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_quantity_cartorderitems_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
