# Generated by Django 5.1.2 on 2024-12-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_address_city_address_order_address_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='send_to',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
